# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255)),
                ('object', models.CharField(max_length=255)),
                ('created', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('event', models.TextField()),
            ],
        ),
    ]
