# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-27 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('anonymous_amount', models.BooleanField(default=False)),
                ('anonymous_donor', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('stripe_charge_id', models.CharField(blank=True, max_length=255, null=True)),
                ('donor_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('donor_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign')),
                ('campaign_participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.VoteParticipant')),
            ],
        ),
    ]
