# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_donation_anonymous'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='anonymous',
            new_name='anonymous_donor',
        ),
    ]
