# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_auto_20171010_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='anonymous_amount',
            field=models.BooleanField(default=False),
        ),
    ]
