# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0017_auto_20171121_1159'),
        ('donation', '0006_auto_20171112_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='campaign_participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.VoteParticipant'),
        ),
    ]
