# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-28 16:19
from __future__ import unicode_literals

import campaign.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0001_initial'),
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_slug', models.SlugField(max_length=255)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('end_date', models.DateTimeField()),
                ('goal', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('trending_score', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('event_location', models.TextField(blank=True)),
                ('website', models.CharField(blank=True, max_length=128)),
                ('category', models.CharField(choices=[('animal', 'Animal'), ('environment', 'Environment'), ('education', 'Education'), ('other', 'Other'), ('religious', 'Religious')], default='other', max_length=255)),
                ('type', models.CharField(choices=[('general', 'General'), ('vote', 'Vote')], default='general', max_length=255)),
                ('campaign_admins', models.ManyToManyField(blank=True, related_name='campaign_admins', to='userprofile.UserProfile')),
                ('campaign_managers', models.ManyToManyField(blank=True, related_name='campaign_managers', to='userprofile.UserProfile')),
                ('campaign_subscribers', models.ManyToManyField(blank=True, related_name='campaign_subscribers', to='userprofile.UserProfile')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='page.Page')),
            ],
            options={
                'permissions': (('manager_edit', 'Manager -- edit Campaign'), ('manager_delete', 'Manager -- delete Campaign'), ('manager_invite', 'Manager -- invite users to manage Campaign'), ('manager_image_edit', 'Manager -- upload media to Campaign'), ('manager_view_dashboard', 'Manager -- view Campaign dashboard')),
            },
        ),
        migrations.CreateModel(
            name='CampaignImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to=campaign.models.upload_to)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('profile_picture', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoteParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to=campaign.models.upload_to)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign')),
            ],
        ),
    ]
