# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 01:36
from __future__ import unicode_literals

import campaign.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteparticipant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=campaign.models.upload_to),
        ),
    ]
