# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/campaigns/images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('campaign_profile', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='campaign_icon',
        ),
        migrations.AddField(
            model_name='campaignimages',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign'),
        ),
    ]
