# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_auto_20170918_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
