# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 00:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_auto_20170804_0035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='slug',
            new_name='campaign_slug',
        ),
    ]
