# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_voteparticipant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='category',
            field=models.CharField(choices=[('animal', 'Animal'), ('environment', 'Environment'), ('education', 'Education'), ('other', 'Other'), ('religious', 'Religious')], default='other', max_length=255),
        ),
    ]
