# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-18 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_campaign_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignimage',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='campaignimage',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
