# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_campaign_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='goal',
            field=models.IntegerField(default=0),
        ),
    ]
