# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_auto_20170919_2131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'permissions': (('manager_edit', 'Manager -- edit Campaign'), ('manager_delete', 'Manager -- delete Campaign'), ('manager_invite', 'Manager -- invite users to manage Campaign'), ('manager_upload', 'Manager -- upload media to Campaign'))},
        ),
    ]
