# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-22 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_auto_20180118_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateTimeField(default='2018-01-01 00:00:00+00'),
            preserve_default=False,
        ),
    ]
