# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_auto_20170921_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignimages',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/campaigns/images/'),
        ),
    ]
