# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_auto_20171001_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'permissions': (('manager_edit', 'Manager -- edit Campaign'), ('manager_delete', 'Manager -- delete Campaign'), ('manager_invite', 'Manager -- invite users to manage Campaign'), ('manager_image_edit', 'Manager -- upload media to Campaign'))},
        ),
    ]
