# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_campaign_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='creator',
            new_name='user',
        ),
    ]
