# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-22 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_auto_20180121_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='goal',
            field=models.IntegerField(),
        ),
    ]
