# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20170818_1521'),
        ('campaign', '0007_auto_20170818_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'permissions': (('manager_edit_campaign', 'Manager -- edit Campaign'), ('manager_delete_campaign', 'Manager -- delete Campaign'), ('manager_invite_campaign', 'Manager -- invite users to manage Campaign'))},
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_admins',
            field=models.ManyToManyField(blank=True, related_name='campaign_admins', to='userprofile.UserProfile'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_managers',
            field=models.ManyToManyField(blank=True, related_name='campaign_managers', to='userprofile.UserProfile'),
        ),
    ]
