# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0007_auto_20171003_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='trending_score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
