# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0007_auto_20170818_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='camp_icon',
            field=models.ImageField(blank=True, null=True, upload_to='media/campaigns/'),
        ),
    ]
