# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0007_auto_20180121_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='type',
            field=models.CharField(choices=[('general', 'General'), ('vote', 'Vote')], default='general', max_length=255),
        ),
    ]
