# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0008_campaign_camp_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='camp_icon',
            new_name='campaign_icon',
        ),
    ]
