# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0008_campaign_trending_score'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CampaignImages',
            new_name='CampaignImage',
        ),
    ]
