# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0008_auto_20170831_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='user',
        ),
    ]
