# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 23:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0009_remove_campaign_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'permissions': (('manager_edit', 'Manager -- edit Campaign'), ('manager_delete', 'Manager -- delete Campaign'), ('manager_invite', 'Manager -- invite users to manage Campaign'))},
        ),
    ]
