# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 20:55
from __future__ import unicode_literals

import campaign.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0009_auto_20171026_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=campaign.models.upload_to),
        ),
    ]
