# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 20:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaign', '0010_auto_20171026_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaignimage',
            old_name='campaign_profile',
            new_name='profile_picture',
        ),
        migrations.AddField(
            model_name='campaignimage',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='campaignimage',
            name='uploaded_by',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
