# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0010_auto_20170831_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaign_slug',
            field=models.SlugField(max_length=255),
        ),
    ]
