# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0011_auto_20171027_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='ended_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
