# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0012_campaign_ended_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='category',
            field=models.CharField(default='education', max_length=255),
            preserve_default=False,
        ),
    ]
