# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0015_auto_20171031_1327'),
        ('campaign', '0013_campaign_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_subscribers',
            field=models.ManyToManyField(blank=True, related_name='campaign_subscribers', to='userprofile.UserProfile'),
        ),
    ]
