# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0014_campaign_campaign_subscribers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'permissions': (('manager_edit', 'Manager -- edit Campaign'), ('manager_delete', 'Manager -- delete Campaign'), ('manager_invite', 'Manager -- invite users to manage Campaign'), ('manager_image_edit', 'Manager -- upload media to Campaign'), ('manager_view_dashboard', 'Manager -- view Campaign dashboard'))},
        ),
    ]
