# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0015_auto_20171116_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='ended_on',
            new_name='end_date',
        ),
    ]
