# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0017_auto_20171121_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='type',
            field=models.CharField(choices=[('event', 'Event'), ('vote', 'Vote')], default='Event', max_length=255),
        ),
    ]
