# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0018_auto_20171121_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='vote_winner_gets',
        ),
    ]
