# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0018_merge_20171003_1531'),
        ('campaign', '0008_campaign_trending_score'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeplan',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign'),
        ),
        migrations.AddField(
            model_name='stripeplan',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.Page'),
        ),
    ]
