# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20171017_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripeplan',
            name='interval',
            field=models.CharField(choices=[('month', 'Monthly')], default='month', max_length=20),
        ),
    ]
