# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_auto_20171020_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeplan',
            name='stripe_plan_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stripeplan',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
