# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('page_slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('donation_count', models.IntegerField(default=0)),
                ('donation_money', models.IntegerField(default=0)),
                ('is_sponsored', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('animal', 'Animal'), ('environment', 'Environment'), ('education', 'Education'), ('religious', 'Religious')], default='', max_length=255)),
                ('admins', models.ManyToManyField(blank=True, related_name='page_admins', to='userprofile.UserProfile')),
                ('managers', models.ManyToManyField(blank=True, related_name='page_managers', to='userprofile.UserProfile')),
                ('subscribers', models.ManyToManyField(blank=True, related_name='subscribers', to='userprofile.UserProfile')),
            ],
            options={
                'permissions': (('manager_edit', 'Manager -- edit Page'), ('manager_delete', 'Manager -- delete Page'), ('manager_invite', 'Manager -- invite users to manage Page')),
            },
        ),
        migrations.CreateModel(
            name='PageIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='media/pages/')),
                ('pageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Page')),
            ],
        ),
    ]
