# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-03 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default='test-page', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
