# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-28 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='type',
            field=models.CharField(choices=[('nonprofit', 'Nonprofit'), ('personal', 'Personal'), ('other', 'Other')], default='', max_length=255),
        ),
    ]
