# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-20 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='stripe_verified',
            field=models.BooleanField(default=True),
        ),
    ]
