# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-17 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20180319_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='stripe_verification_requested',
            field=models.BooleanField(default=False),
        ),
    ]
