# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-03 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20170803_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='donation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='page',
            name='donation_money',
            field=models.IntegerField(default=0),
        ),
    ]
