# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-16 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_page_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='stripe_verified',
            field=models.BooleanField(default=False),
        ),
    ]
