# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_pageimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageicon',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='media/pages/icon/'),
        ),
    ]
