# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-28 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20180127_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='category',
            field=models.CharField(choices=[('animal', 'Animal'), ('arts', 'Arts'), ('community', 'Community'), ('education', 'Education'), ('emergencies', 'Emergencies'), ('environmental', 'Environmental'), ('family', 'Family'), ('humanitarian', 'Humanitarian Aid'), ('medical', 'Medical'), ('memorial', 'Memorial'), ('other', 'Other'), ('religious', 'Religious'), ('sports', 'Sports'), ('stem', 'STEM (Science, Technology, Engineering, and Math)'), ('veterans', 'Veterans')], default='other', max_length=255),
        ),
    ]
