# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20170918_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
