# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20170803_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='slug',
            new_name='page_slug',
        ),
    ]
