# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 02:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20170913_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pageicon',
            old_name='pageid',
            new_name='page',
        ),
    ]
