# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
        ('page', '0004_auto_20170804_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='admins',
            field=models.ManyToManyField(to='userprofile.UserProfile'),
        ),
    ]
