# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20170919_2131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'permissions': (('manager_edit', 'Manager -- edit Page'), ('manager_delete', 'Manager -- delete Page'), ('manager_invite', 'Manager -- invite users to manage Page'), ('manager_upload', 'Manager -- upload media to Page'))},
        ),
    ]
