# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_page_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.CharField(choices=[('', '-----------'), ('animal', 'Animal'), ('environment', 'Environment'), ('education', 'Education'), ('religious', 'Religious')], default='', max_length=255),
        ),
    ]
