# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_auto_20170922_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='stripe_account_id',
            field=models.CharField(default='NONE', max_length=255),
            preserve_default=False,
        ),
    ]
