# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_page_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='admins',
            field=models.ManyToManyField(blank=True, to='userprofile.UserProfile'),
        ),
    ]
