# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_auto_20170922_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageimages',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/pages/images/'),
        ),
    ]
