# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 18:43
from __future__ import unicode_literals

from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_auto_20170805_0209'),
    ]

    operations = [
        TrigramExtension(),
        UnaccentExtension(),
    ]
