# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_page_stripe_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
