# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_auto_20170925_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='address_line1',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='page',
            name='ein',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='zipcode',
            field=models.CharField(default='11111', max_length=5),
            preserve_default=False,
        ),
    ]
