# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_auto_20170807_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='category',
            field=models.CharField(choices=[('animal', 'Animal'), ('environment', 'Environment'), ('education', 'Education'), ('religious', 'Religious')], default='', max_length=255),
        ),
    ]
