# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_auto_20170925_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='stripe_bank_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
