# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20170804_1806'),
        ('page', '0009_auto_20170807_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='userprofile.UserProfile'),
        ),
        migrations.AlterField(
            model_name='page',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admins', to='userprofile.UserProfile'),
        ),
    ]
