# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_auto_20170809_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_sponsored',
            field=models.BooleanField(default=False),
        ),
    ]
