# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_page_stripe_bank_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='type',
            field=models.CharField(choices=[('nonprofit', 'Nonprofit'), ('personal', 'Personal'), ('religious', 'Religious'), ('other', 'Other')], default='', max_length=255),
        ),
    ]
