# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_auto_20170927_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='page',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='page',
            name='website',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
