# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_page_is_sponsored'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'permissions': (('manager_edit_page', 'Manager -- edit Page'),)},
        ),
    ]
