# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0013_page_nonprofit_number'),
        ('page', '0007_auto_20170928_1330'),
    ]

    operations = [
    ]
