# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0014_merge_20171002_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'permissions': (('manager_edit', 'Manager -- edit Page'), ('manager_delete', 'Manager -- delete Page'), ('manager_invite', 'Manager -- invite users to manage Page'), ('manager_image_edit', 'Manager -- upload and edit media on Page'))},
        ),
    ]
