# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0014_merge_20171002_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='trending_score',
            field=models.IntegerField(default=0),
        ),
    ]
