# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0015_auto_20170831_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='page_admins', to='userprofile.UserProfile'),
        ),
        migrations.AlterField(
            model_name='page',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='page_managers', to='userprofile.UserProfile'),
        ),
    ]
