# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0015_page_trending_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='trending_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
