# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0016_auto_20170831_1918'),
        ('page', '0012_page_icon'),
    ]

    operations = [
    ]
