# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0017_merge_20170905_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
