# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0017_auto_20171003_1523'),
        ('page', '0015_auto_20171003_1316'),
    ]

    operations = [
    ]
