# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0017_merge_20170905_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='media/pages/')),
            ],
        ),
        migrations.RemoveField(
            model_name='page',
            name='icon',
        ),
    ]
