# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0018_merge_20171003_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pageimages',
            old_name='page_profile',
            new_name='profile_picture',
        ),
    ]
