# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import page.models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0019_auto_20171023_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageimages',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=page.models.upload_to),
        ),
    ]
