# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0021_auto_20171023_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageimage',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
