# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0022_remove_pageimage_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageimage',
            name='page',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='page.Page'),
            preserve_default=False,
        ),
    ]
