# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0023_auto_20170915_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='type',
            field=models.CharField(choices=[('organization', 'Organization'), ('personal', 'Personal')], default='', max_length=255),
        ),
    ]
