# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0025_auto_20171130_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='nonprofit_number',
        ),
    ]
