# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0027_auto_20171204_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='category',
            field=models.CharField(choices=[('animal', 'Animal'), ('environment', 'Environment'), ('education', 'Education'), ('other', 'Other'), ('religious', 'Religious')], default='other', max_length=255),
        ),
    ]
