# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0028_auto_20171204_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='tos_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
