# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0029_page_tos_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='page',
            name='contact_phone',
        ),
        migrations.AlterField(
            model_name='page',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='page',
            name='ein',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
