# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-29 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0031_auto_20171218_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageimage',
            name='height',
            field=models.IntegerField(default=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pageimage',
            name='width',
            field=models.IntegerField(default=128),
            preserve_default=False,
        ),
    ]
