# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-05 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0032_auto_20171228_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageimage',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pageimage',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
