# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20171114_1816'),
        ('votes', '0002_auto_20171113_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.Reply'),
        ),
    ]
