# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20170919_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
