# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20170919_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='upvotes',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='upvotes',
        ),
    ]
