# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 23:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('error', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='error',
            name='message',
        ),
    ]
