# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 23:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('error', '0002_remove_error_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='error',
            old_name='created_on',
            new_name='date',
        ),
    ]
