# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error', '0004_auto_20171220_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='message',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
