# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='notification_email_campaign_donation',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='notification_email_campaign_ticket_purchased',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='notification_email_campaign_ticket_sold_out',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='notification_email_page_donation',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notification_email_donation',
            field=models.BooleanField(default=True),
        ),
    ]
