# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-18 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userimage',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
