# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ('first_name', 'last_name')},
        ),
    ]
