# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20170919_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userimages',
            old_name='user_profile',
            new_name='profile_picture',
        ),
    ]
