# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20180202_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='notification_email_campaign_goal_reached',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='notification_email_campaign_manager',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='notification_email_campaign_voted',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='notification_email_page_created',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='notification_email_page_manager',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='notification_email_pagefund_news',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='notification_email_recurring_donation',
        ),
    ]
