# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20170804_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='avatar'),
        ),
    ]
