# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-20 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20180118_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
