# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20170920_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(default='1990-06-14'),
            preserve_default=False,
        ),
    ]
