# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20170927_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimages',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/user/images/'),
        ),
    ]
