# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_stripecard'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecard',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
