# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20171003_1954'),
        ('userprofile', '0009_stripecard_name'),
    ]

    operations = [
    ]
