# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_merge_20171006_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecard',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
