# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_stripecard_default'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserImages',
            new_name='UserImage',
        ),
    ]
