# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import userprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0012_auto_20171026_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=userprofile.models.upload_to),
        ),
    ]
