# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_auto_20171026_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecard',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
