# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import userprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0015_auto_20171031_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=userprofile.models.upload_to),
        ),
    ]
