# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-13 00:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalinvitation',
            name='invite_from',
        ),
        migrations.DeleteModel(
            name='GeneralInvitation',
        ),
    ]
