# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerinvitation',
            name='manager_upload',
            field=models.BooleanField(default=False),
        ),
    ]
