# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0014_page_managers'),
        ('invitations', '0002_auto_20170823_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerinvitation',
            name='page',
            field=models.OneToOneField(default='4', on_delete=django.db.models.deletion.CASCADE, to='page.Page'),
            preserve_default=False,
        ),
    ]
