# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 21:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import invitations.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invitations', '0002_managerinvitation_manager_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expired', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('declined', models.BooleanField(default=False)),
                ('key', models.CharField(default=invitations.models.random_key, max_length=32)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('invite_to', models.EmailField(max_length=254)),
                ('invite_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='managerinvitation',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
