# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 00:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_managerinvitation_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerinvitation',
            name='invite_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
