# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_auto_20170922_1620'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegularInvitation',
            new_name='GeneralInvitation',
        ),
    ]
