# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import invitations.models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_auto_20170922_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPasswordRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.EmailField(max_length=254)),
                ('expired', models.BooleanField(default=False)),
                ('key', models.CharField(default=invitations.models.random_key, max_length=32)),
            ],
        ),
    ]
