# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 00:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_auto_20170824_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerinvitation',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Page'),
        ),
    ]
