# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0005_forgotpasswordrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managerinvitation',
            old_name='manager_upload',
            new_name='manager_image_edit',
        ),
    ]
