# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0005_auto_20170824_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managerinvitation',
            old_name='can_delete',
            new_name='manager_delete_page',
        ),
        migrations.RenameField(
            model_name='managerinvitation',
            old_name='can_edit',
            new_name='manager_edit_page',
        ),
        migrations.RenameField(
            model_name='managerinvitation',
            old_name='can_invite',
            new_name='manager_invite_page',
        ),
    ]
