# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0006_auto_20170824_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerinvitation',
            name='declined',
            field=models.BooleanField(default=False),
        ),
    ]
