# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0006_auto_20171003_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerinvitation',
            name='manager_view_dashboard',
            field=models.BooleanField(default=False),
        ),
    ]
