# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 22:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import invitations.models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0009_remove_campaign_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invitations', '0007_managerinvitation_declined'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignManagerInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expired', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('declined', models.BooleanField(default=False)),
                ('key', models.CharField(default=invitations.models.random_key, max_length=32)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('invite_to', models.EmailField(max_length=254)),
                ('manager_edit_page', models.BooleanField(default=False)),
                ('manager_delete_page', models.BooleanField(default=False)),
                ('manager_invite_page', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign')),
                ('invite_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='ManagerInvitation',
            new_name='PageManagerInvitation',
        ),
    ]
