# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0008_auto_20170831_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaignmanagerinvitation',
            old_name='manager_delete_page',
            new_name='manager_delete_campaign',
        ),
        migrations.RenameField(
            model_name='campaignmanagerinvitation',
            old_name='manager_edit_page',
            new_name='manager_edit_campaign',
        ),
        migrations.RenameField(
            model_name='campaignmanagerinvitation',
            old_name='manager_invite_page',
            new_name='manager_invite_campaign',
        ),
    ]
