# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 22:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import invitations.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaign', '0009_remove_campaign_user'),
        ('page', '0014_page_managers'),
        ('invitations', '0009_auto_20170831_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expired', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('declined', models.BooleanField(default=False)),
                ('key', models.CharField(default=invitations.models.random_key, max_length=32)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('invite_to', models.EmailField(max_length=254)),
                ('manager_edit', models.BooleanField(default=False)),
                ('manager_delete', models.BooleanField(default=False)),
                ('manager_invite', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign')),
                ('invite_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.Page')),
            ],
        ),
        migrations.RemoveField(
            model_name='campaignmanagerinvitation',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='campaignmanagerinvitation',
            name='invite_from',
        ),
        migrations.RemoveField(
            model_name='pagemanagerinvitation',
            name='invite_from',
        ),
        migrations.RemoveField(
            model_name='pagemanagerinvitation',
            name='page',
        ),
        migrations.DeleteModel(
            name='CampaignManagerInvitation',
        ),
        migrations.DeleteModel(
            name='PageManagerInvitation',
        ),
    ]
