# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-31 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0002_auto_20171114_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
